server:
  #端口号
  port: 1994


spring:
  datasource:
    url: jdbc:mysql://dev-db.joinboom.net:3306/cgw
    username: cgw-dev
    password: joinboom
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
  mapperLocations: classpath:/mybatis/*Mapper.xml
  type-aliases-package: com.zbjk.general.cgw.domain
